# Generated by Django 4.2.14 on 2024-07-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('summary', models.TextField()),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
            ],
        ),
    ]
